FROM python:3.12-slim
WORKDIR /app
COPY worker/requirements_worker.txt .
RUN pip install --no-cache-dir -r requirements_worker.txt


COPY worker /app/worker


COPY cor_pass /app/cor_pass
COPY en-basic /app/en-basic

ENV PYTHONPATH=/app

EXPOSE 45762

CMD ["python", "worker/main_with_websocket.py"]