"""objects_modbus

Revision ID: 0ed5c3bce5cc
Revises: 995944bbbe87
Create Date: 2025-12-08 14:58:59.779192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ed5c3bce5cc'
down_revision: Union[str, None] = '995944bbbe87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websocket_broadcast_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False, comment='Имя задачи'),
    sa.Column('session_id', sa.String(), nullable=False, comment='Session ID устройства'),
    sa.Column('command_type', sa.String(), nullable=False, comment='Тип команды: pi30 | modbus_read'),
    sa.Column('command_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Полезная нагрузка команды (для pi30: {pi30: hex}, для modbus_read: {hex_data: ...})'),
    sa.Column('interval_seconds', sa.Integer(), nullable=False, comment='Интервал отправки команды в секундах'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли задача рассылки'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True, comment='Кто создал задачу (user_id или admin)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websocket_broadcast_tasks_session_id'), 'websocket_broadcast_tasks', ['session_id'], unique=False)
    op.create_table('device_polling_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('energetic_object_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False, comment='Тип задачи: cerbo_collection | schedule_check | modbus_registers | custom_command'),
    sa.Column('command_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Конфигурация команд в JSON формате (какие регистры читать, параметры команды)'),
    sa.Column('interval_seconds', sa.Integer(), nullable=False, comment='Интервал опроса в секундах'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли задача опроса'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['energetic_object_id'], ['energetic_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_polling_tasks_energetic_object_id'), 'device_polling_tasks', ['energetic_object_id'], unique=False)
    op.create_table('user_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('token', sa.String(length=250), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_invitations_email'), 'user_invitations', ['email'], unique=False)
    op.create_index('ix_user_invitations_email_not_used', 'user_invitations', ['email', 'is_used'], unique=False)
    op.create_index(op.f('ix_user_invitations_token'), 'user_invitations', ['token'], unique=True)
    op.create_index('ix_user_invitations_token_not_used', 'user_invitations', ['token', 'is_used'], unique=False)
    op.add_column('corporate_clients', sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True, comment='Текущий баланс компании в финбэке (обновляется через вебхук)'))
    op.add_column('corporate_clients', sa.Column('last_balance_update', sa.DateTime(timezone=True), nullable=True, comment='Время последнего обновления баланса из финбэка'))
    op.alter_column('corporate_clients', 'fuel_limit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Кредитный лимит - на сколько компания может уйти в минус (грн)',
               existing_comment='Лимит компании на топливо (грн)',
               existing_nullable=False,
               existing_server_default=sa.text('16000.00'))
    op.add_column('energetic_objects', sa.Column('modbus_config_file', sa.String(), nullable=True, comment='Имя файла конфигурации Modbus регистров (например: victron_cerbo_gx.json)'))
    op.add_column('energetic_objects', sa.Column('telegram_chat_ids', sa.String(), nullable=True))
    op.add_column('sibionics_devices', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('sibionics_devices', sa.Column('device_type', sa.String(length=50), nullable=True))
    op.add_column('sibionics_devices', sa.Column('sn', sa.String(length=255), nullable=True))
    op.add_column('sibionics_devices', sa.Column('model', sa.String(length=255), nullable=True))
    op.add_column('sibionics_devices', sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('sibionics_devices', 'auth_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint('uq_auth_device', 'sibionics_devices', type_='unique')
    op.create_index('idx_sibionics_device_user_id', 'sibionics_devices', ['user_id'], unique=False)
    op.create_foreign_key(None, 'sibionics_devices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sibionics_devices', type_='foreignkey')
    op.drop_index('idx_sibionics_device_user_id', table_name='sibionics_devices')
    op.create_unique_constraint('uq_auth_device', 'sibionics_devices', ['auth_id', 'device_id'])
    op.alter_column('sibionics_devices', 'auth_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('sibionics_devices', 'last_sync')
    op.drop_column('sibionics_devices', 'model')
    op.drop_column('sibionics_devices', 'sn')
    op.drop_column('sibionics_devices', 'device_type')
    op.drop_column('sibionics_devices', 'user_id')
    op.drop_column('energetic_objects', 'telegram_chat_ids')
    op.drop_column('energetic_objects', 'modbus_config_file')
    op.alter_column('corporate_clients', 'fuel_limit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Лимит компании на топливо (грн)',
               existing_comment='Кредитный лимит - на сколько компания может уйти в минус (грн)',
               existing_nullable=False,
               existing_server_default=sa.text('16000.00'))
    op.drop_column('corporate_clients', 'last_balance_update')
    op.drop_column('corporate_clients', 'current_balance')
    op.drop_index('ix_user_invitations_token_not_used', table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_token'), table_name='user_invitations')
    op.drop_index('ix_user_invitations_email_not_used', table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_email'), table_name='user_invitations')
    op.drop_table('user_invitations')
    op.drop_index(op.f('ix_device_polling_tasks_energetic_object_id'), table_name='device_polling_tasks')
    op.drop_table('device_polling_tasks')
    op.drop_index(op.f('ix_websocket_broadcast_tasks_session_id'), table_name='websocket_broadcast_tasks')
    op.drop_table('websocket_broadcast_tasks')
    # ### end Alembic commands ###
