"""add laboratory table  v1.1.25

Revision ID: 1f802a4585b7
Revises: 434b3abc70ce
Create Date: 2025-10-21 11:58:33.545199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f802a4585b7'
down_revision: Union[str, None] = '434b3abc70ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_laboratories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lab_name', sa.String(length=255), nullable=True),
    sa.Column('lab_email', sa.String(length=255), nullable=True),
    sa.Column('lab_phone_number', sa.String(length=255), nullable=True),
    sa.Column('lab_website', sa.String(length=255), nullable=True),
    sa.Column('lab_address', sa.String(length=255), nullable=True),
    sa.Column('lab_logo_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lab_logo_data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('prescription_files', 'issue_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('prescription_files', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescription_files', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('prescription_files', 'issue_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_table('medical_laboratories')
    # ### end Alembic commands ###
