"""add_balance_fields_to_corporate_clients_v1_4_3

Revision ID: 26d4cc00b3f3
Revises: 8056c4640370
Create Date: 2025-12-04 11:23:29.563254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d4cc00b3f3'
down_revision: Union[str, None] = '8056c4640370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_clients', sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True, comment='Текущий баланс компании в финбэке (обновляется через вебхук)'))
    op.add_column('corporate_clients', sa.Column('last_balance_update', sa.DateTime(timezone=True), nullable=True, comment='Время последнего обновления баланса из финбэка'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_clients', 'last_balance_update')
    op.drop_column('corporate_clients', 'current_balance')
    # ### end Alembic commands ###
