"""energetic_devices_models_v1_4_7

Revision ID: 34310b7ed291
Revises: 4ac0e823ca26
Create Date: 2025-12-17 12:20:18.676787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '34310b7ed291'
down_revision: Union[str, None] = '4ac0e823ca26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reuse existing Postgres ENUM type for access level to avoid duplicate type creation
    accesslevel_enum = postgresql.ENUM('read', 'read_write', 'share', name='accesslevel', create_type=False)
    op.create_table('energetic_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('owner_cor_id', sa.String(length=250), nullable=False),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energetic_devices_device_id'), 'energetic_devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_energetic_devices_owner_cor_id'), 'energetic_devices', ['owner_cor_id'], unique=False)
    op.create_table('energetic_device_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('granting_user_cor_id', sa.String(length=36), nullable=True),
    sa.Column('accessing_user_cor_id', sa.String(length=36), nullable=False),
    sa.Column('access_level', accesslevel_enum, nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accessing_user_cor_id'], ['users.cor_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['energetic_devices.id'], ),
    sa.ForeignKeyConstraint(['granting_user_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energetic_device_access')
    op.drop_index(op.f('ix_energetic_devices_owner_cor_id'), table_name='energetic_devices')
    op.drop_index(op.f('ix_energetic_devices_device_id'), table_name='energetic_devices')
    op.drop_table('energetic_devices')
    # ### end Alembic commands ###
