"""add users prescriptions table  v1.1.24

Revision ID: 434b3abc70ce
Revises: 0795a77bf44c
Create Date: 2025-10-20 12:46:11.508158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434b3abc70ce'
down_revision: Union[str, None] = '0795a77bf44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_cor_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size_kb', sa.Float(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['user_cor_id'], ['users.cor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription_files')
    # ### end Alembic commands ###
