"""add_first_aid_kit_share_v1_4_6

Revision ID: 4ac0e823ca26
Revises: 6fa741b5f894
Create Date: 2025-12-12 12:18:38.811561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ac0e823ca26'
down_revision: Union[str, None] = '6fa741b5f894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('first_aid_kit_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kit_id', sa.String(length=36), nullable=False),
    sa.Column('from_user_cor_id', sa.String(length=36), nullable=False),
    sa.Column('to_user_cor_id', sa.String(length=36), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', 'FAILED', name='firstaidkitsharestatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_user_cor_id'], ['users.cor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kit_id'], ['first_aid_kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_cor_id'], ['users.cor_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_first_aid_kit_shares_from_user', 'first_aid_kit_shares', ['from_user_cor_id'], unique=False)
    op.create_index('idx_first_aid_kit_shares_kit_id', 'first_aid_kit_shares', ['kit_id'], unique=False)
    op.create_index('idx_first_aid_kit_shares_to_user', 'first_aid_kit_shares', ['to_user_cor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_first_aid_kit_shares_to_user', table_name='first_aid_kit_shares')
    op.drop_index('idx_first_aid_kit_shares_kit_id', table_name='first_aid_kit_shares')
    op.drop_index('idx_first_aid_kit_shares_from_user', table_name='first_aid_kit_shares')
    op.drop_table('first_aid_kit_shares')
    # ### end Alembic commands ###
