"""add_device_polling_tasks_and_modbus_config_file_v1_4_1

Revision ID: 6f59baac5d25
Revises: a473e95f0c2e
Create Date: 2025-12-03 12:38:28.681291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f59baac5d25'
down_revision: Union[str, None] = 'a473e95f0c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_polling_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('energetic_object_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False, comment='Тип задачи: cerbo_collection | schedule_check | modbus_registers | custom_command'),
    sa.Column('command_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Конфигурация команд в JSON формате (какие регистры читать, параметры команды)'),
    sa.Column('interval_seconds', sa.Integer(), nullable=False, comment='Интервал опроса в секундах'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли задача опроса'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['energetic_object_id'], ['energetic_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_polling_tasks_energetic_object_id'), 'device_polling_tasks', ['energetic_object_id'], unique=False)
    op.add_column('energetic_objects', sa.Column('modbus_config_file', sa.String(), nullable=True, comment='Имя файла конфигурации Modbus регистров (например: victron_cerbo_gx.json)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('energetic_objects', 'modbus_config_file')
    op.drop_index(op.f('ix_device_polling_tasks_energetic_object_id'), table_name='device_polling_tasks')
    op.drop_table('device_polling_tasks')
    # ### end Alembic commands ###
