"""add_corporate_employee_invitations_v1_4_5

Revision ID: 6fa741b5f894
Revises: ce304dcffc2f
Create Date: 2025-12-10 11:24:56.450894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa741b5f894'
down_revision: Union[str, None] = 'ce304dcffc2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_employee_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('limit_amount', sa.Integer(), nullable=False),
    sa.Column('limit_period', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Integer(), nullable=False),
    sa.Column('created_cor_id', sa.String(length=36), nullable=True),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corp_emp_inv_company_id', 'corporate_employee_invitations', ['company_id'], unique=False)
    op.create_index('ix_corp_emp_inv_email_not_used', 'corporate_employee_invitations', ['email', 'is_used'], unique=False)
    op.create_index(op.f('ix_corporate_employee_invitations_email'), 'corporate_employee_invitations', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporate_employee_invitations_email'), table_name='corporate_employee_invitations')
    op.drop_index('ix_corp_emp_inv_email_not_used', table_name='corporate_employee_invitations')
    op.drop_index('ix_corp_emp_inv_company_id', table_name='corporate_employee_invitations')
    op.drop_table('corporate_employee_invitations')
    # ### end Alembic commands ###
