"""objects_worker

Revision ID: 704184c5114b
Revises: 0ed5c3bce5cc
Create Date: 2025-12-11 10:50:22.836760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '704184c5114b'
down_revision: Union[str, None] = '0ed5c3bce5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_employee_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('limit_amount', sa.Integer(), nullable=False),
    sa.Column('limit_period', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Integer(), nullable=False),
    sa.Column('created_cor_id', sa.String(length=36), nullable=True),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corp_emp_inv_company_id', 'corporate_employee_invitations', ['company_id'], unique=False)
    op.create_index('ix_corp_emp_inv_email_not_used', 'corporate_employee_invitations', ['email', 'is_used'], unique=False)
    op.create_index(op.f('ix_corporate_employee_invitations_email'), 'corporate_employee_invitations', ['email'], unique=False)
    op.add_column('first_aid_kits', sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Является ли аптечка основной'))
    op.add_column('medicine_intakes', sa.Column('first_aid_kit_id', sa.String(length=36), nullable=True, comment='Аптечка, из которой списано лекарство'))
    op.add_column('medicine_intakes', sa.Column('taken_quantity', sa.Integer(), nullable=True, comment='Количество принятых таблеток/доз'))
    op.create_foreign_key(None, 'medicine_intakes', 'first_aid_kits', ['first_aid_kit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medicine_intakes', type_='foreignkey')
    op.drop_column('medicine_intakes', 'taken_quantity')
    op.drop_column('medicine_intakes', 'first_aid_kit_id')
    op.drop_column('first_aid_kits', 'is_primary')
    op.drop_index(op.f('ix_corporate_employee_invitations_email'), table_name='corporate_employee_invitations')
    op.drop_index('ix_corp_emp_inv_email_not_used', table_name='corporate_employee_invitations')
    op.drop_index('ix_corp_emp_inv_company_id', table_name='corporate_employee_invitations')
    op.drop_table('corporate_employee_invitations')
    # ### end Alembic commands ###
