"""add_ws_polling_table_v1_4_2

Revision ID: 8056c4640370
Revises: 6f59baac5d25
Create Date: 2025-12-03 15:34:26.226229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8056c4640370'
down_revision: Union[str, None] = '6f59baac5d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websocket_broadcast_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False, comment='Имя задачи'),
    sa.Column('session_id', sa.String(), nullable=False, comment='Session ID устройства'),
    sa.Column('command_type', sa.String(), nullable=False, comment='Тип команды: pi30 | modbus_read'),
    sa.Column('command_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Полезная нагрузка команды (для pi30: {pi30: hex}, для modbus_read: {hex_data: ...})'),
    sa.Column('interval_seconds', sa.Integer(), nullable=False, comment='Интервал отправки команды в секундах'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли задача рассылки'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True, comment='Кто создал задачу (user_id или admin)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websocket_broadcast_tasks_session_id'), 'websocket_broadcast_tasks', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websocket_broadcast_tasks_session_id'), table_name='websocket_broadcast_tasks')
    op.drop_table('websocket_broadcast_tasks')
    # ### end Alembic commands ###
