"""objects

Revision ID: 995944bbbe87
Revises: ab02528376c1
Create Date: 2025-11-28 13:50:23.831467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '995944bbbe87'
down_revision: Union[str, None] = 'ab02528376c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energetic_objects', sa.Column('vendor', sa.String(), nullable=True, comment='Производитель/вендор инвертора'))
    op.alter_column('energetic_objects', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Часовой пояс объекта (например: Europe/Kiev)',
               existing_server_default=sa.text("'Europe/Kiev'::character varying"))
    op.drop_column('energetic_objects', 'modbus_registers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energetic_objects', sa.Column('modbus_registers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Карта регистров Modbus (динамическая структура в формате JSON)'))
    op.alter_column('energetic_objects', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Часовой пояс объекта (например: Europe/Kiev)',
               existing_server_default=sa.text("'Europe/Kiev'::character varying"))
    op.drop_column('energetic_objects', 'vendor')
    # ### end Alembic commands ###
