"""add_manual_glucose_device_v1_4_0

Revision ID: a473e95f0c2e
Revises: c904b1a16893
Create Date: 2025-12-02 13:01:01.428455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a473e95f0c2e'
down_revision: Union[str, None] = 'c904b1a16893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sibionics_devices', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('sibionics_devices', sa.Column('device_type', sa.String(length=50), nullable=True))
    op.add_column('sibionics_devices', sa.Column('sn', sa.String(length=255), nullable=True))
    op.add_column('sibionics_devices', sa.Column('model', sa.String(length=255), nullable=True))
    op.add_column('sibionics_devices', sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('sibionics_devices', 'auth_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint('uq_auth_device', 'sibionics_devices', type_='unique')
    op.create_index('idx_sibionics_device_user_id', 'sibionics_devices', ['user_id'], unique=False)
    op.create_foreign_key(None, 'sibionics_devices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sibionics_devices', type_='foreignkey')
    op.drop_index('idx_sibionics_device_user_id', table_name='sibionics_devices')
    op.create_unique_constraint('uq_auth_device', 'sibionics_devices', ['auth_id', 'device_id'])
    op.alter_column('sibionics_devices', 'auth_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('sibionics_devices', 'last_sync')
    op.drop_column('sibionics_devices', 'model')
    op.drop_column('sibionics_devices', 'sn')
    op.drop_column('sibionics_devices', 'device_type')
    op.drop_column('sibionics_devices', 'user_id')
    # ### end Alembic commands ###
