"""add_soft_delete_to_corporate_clients_v1_2_4

Revision ID: ab02528376c1
Revises: dc2e405b466f
Create Date: 2025-11-25 10:59:59.749723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab02528376c1'
down_revision: Union[str, None] = 'dc2e405b466f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_clients', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'))
    op.drop_constraint('corporate_clients_company_name_key', 'corporate_clients', type_='unique')
    op.drop_constraint('corporate_clients_tax_id_key', 'corporate_clients', type_='unique')
    op.create_index('uq_corp_client_company_name', 'corporate_clients', ['company_name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_corp_client_tax_id', 'corporate_clients', ['tax_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_corp_client_tax_id', table_name='corporate_clients', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_corp_client_company_name', table_name='corporate_clients', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint('corporate_clients_tax_id_key', 'corporate_clients', ['tax_id'])
    op.create_unique_constraint('corporate_clients_company_name_key', 'corporate_clients', ['company_name'])
    op.drop_column('corporate_clients', 'deleted_at')
    # ### end Alembic commands ###
