"""add_user_invitations_table_v1_2_7

Revision ID: c904b1a16893
Revises: b1a2c3d4e5f6
Create Date: 2025-12-01 12:30:15.995504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c904b1a16893'
down_revision: Union[str, None] = 'b1a2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('token', sa.String(length=250), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_invitations_email'), 'user_invitations', ['email'], unique=False)
    op.create_index('ix_user_invitations_email_not_used', 'user_invitations', ['email', 'is_used'], unique=False)
    op.create_index(op.f('ix_user_invitations_token'), 'user_invitations', ['token'], unique=True)
    op.create_index('ix_user_invitations_token_not_used', 'user_invitations', ['token', 'is_used'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_invitations_token_not_used', table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_token'), table_name='user_invitations')
    op.drop_index('ix_user_invitations_email_not_used', table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_email'), table_name='user_invitations')
    op.drop_table('user_invitations')
    # ### end Alembic commands ###
