"""add_is_primary_and_first_aid_kit_tracking_v1_4_4

Revision ID: ce304dcffc2f
Revises: 26d4cc00b3f3
Create Date: 2025-12-09 13:25:38.978308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce304dcffc2f'
down_revision: Union[str, None] = '26d4cc00b3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corporate_clients', 'fuel_limit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Кредитный лимит - на сколько компания может уйти в минус (грн)',
               existing_comment='Лимит компании на топливо (грн)',
               existing_nullable=False,
               existing_server_default=sa.text('16000.00'))
    op.add_column('first_aid_kits', sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Является ли аптечка основной', server_default='false'))
    
    # Назначаем первую созданную аптечку каждого пользователя основной
    connection = op.get_bind()
    
    # Получаем первую аптечку для каждого пользователя (самая старая по created_at)
    result = connection.execute(sa.text("""
        SELECT DISTINCT ON (user_cor_id) id, user_cor_id
        FROM first_aid_kits
        ORDER BY user_cor_id, created_at ASC
    """))
    
    first_kits = result.fetchall()
    
    # Устанавливаем is_primary=true для первых аптечек
    for kit_id, user_cor_id in first_kits:
        connection.execute(
            sa.text("UPDATE first_aid_kits SET is_primary = true WHERE id = :kit_id"),
            {"kit_id": kit_id}
        )
    
    # Убираем server_default после миграции данных
    op.alter_column('first_aid_kits', 'is_primary', server_default=None)
    
    op.add_column('medicine_intakes', sa.Column('first_aid_kit_id', sa.String(length=36), nullable=True, comment='Аптечка, из которой списано лекарство'))
    op.add_column('medicine_intakes', sa.Column('taken_quantity', sa.Integer(), nullable=True, comment='Количество принятых таблеток/доз'))
    op.create_foreign_key(None, 'medicine_intakes', 'first_aid_kits', ['first_aid_kit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medicine_intakes', type_='foreignkey')
    op.drop_column('medicine_intakes', 'taken_quantity')
    op.drop_column('medicine_intakes', 'first_aid_kit_id')
    op.drop_column('first_aid_kits', 'is_primary')
    op.alter_column('corporate_clients', 'fuel_limit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Лимит компании на топливо (грн)',
               existing_comment='Кредитный лимит - на сколько компания может уйти в минус (грн)',
               existing_nullable=False,
               existing_server_default=sa.text('16000.00'))
    # ### end Alembic commands ###
