"""Rebuild migration 10.11.2025_2

Revision ID: dcc369e4982f
Revises: fd8ded0a70b2
Create Date: 2025-11-11 11:21:58.538159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc369e4982f'
down_revision: Union[str, None] = 'fd8ded0a70b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_backend_auth',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False, comment='Название сервиса (finance_backend)'),
    sa.Column('api_endpoint', sa.String(length=500), nullable=False, comment='URL бэкенда финансов'),
    sa.Column('totp_secret', sa.LargeBinary(), nullable=False, comment='Зашифрованный TOTP секрет'),
    sa.Column('totp_interval', sa.Integer(), nullable=True, comment='Интервал TOTP в секундах'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Активна ли интеграция'),
    sa.Column('last_successful_auth', sa.DateTime(timezone=True), nullable=True, comment='Последняя успешная авторизация'),
    sa.Column('last_failed_auth', sa.DateTime(timezone=True), nullable=True, comment='Последняя неудачная авторизация'),
    sa.Column('failed_attempts', sa.Integer(), nullable=True, comment='Количество неудачных попыток подряд'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_index('idx_finance_auth_service', 'finance_backend_auth', ['service_name'], unique=False)
    op.create_table('financiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('financier_cor_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['financier_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financier_cor_id')
    )
    op.create_table('fuel_station_qr_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_cor_id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False, comment='Уникальный токен сессии'),
    sa.Column('totp_code', sa.String(length=10), nullable=False, comment='TOTP код на момент генерации'),
    sa.Column('timestamp_token', sa.String(length=255), nullable=False, comment='Timestamp токен для защиты от replay атак'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Время создания QR кода'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Время истечения QR кода'),
    sa.Column('is_used', sa.Boolean(), nullable=True, comment='Был ли использован QR код'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Время использования'),
    sa.ForeignKeyConstraint(['user_cor_id'], ['users.cor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fuel_qr_created', 'fuel_station_qr_sessions', ['created_at'], unique=False)
    op.create_index('idx_fuel_qr_token', 'fuel_station_qr_sessions', ['session_token'], unique=False)
    op.create_index('idx_fuel_qr_user', 'fuel_station_qr_sessions', ['user_cor_id'], unique=False)
    op.create_index(op.f('ix_fuel_station_qr_sessions_session_token'), 'fuel_station_qr_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_fuel_station_qr_sessions_user_cor_id'), 'fuel_station_qr_sessions', ['user_cor_id'], unique=False)
    op.drop_constraint('device_access_granting_user_id_fkey', 'device_access', type_='foreignkey')
    op.drop_constraint('device_access_accessing_user_id_fkey', 'device_access', type_='foreignkey')
    op.create_foreign_key(None, 'device_access', 'users', ['accessing_user_id'], ['cor_id'])
    op.create_foreign_key(None, 'device_access', 'users', ['granting_user_id'], ['cor_id'])
    op.drop_constraint('devices_user_id_fkey', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'users', ['user_id'], ['cor_id'])
    op.drop_constraint('doctors_doctor_id_fkey', 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'users', ['doctor_id'], ['cor_id'])
    op.add_column('energetic_objects', sa.Column('ip_address', sa.String(), nullable=True, comment='IP-адрес объекта'))
    op.add_column('energetic_objects', sa.Column('port', sa.Integer(), nullable=True, comment='Порт объекта'))
    op.add_column('energetic_objects', sa.Column('inverter_login', sa.String(), nullable=True, comment='Логин для доступа к инвертору'))
    op.add_column('energetic_objects', sa.Column('inverter_password', sa.String(), nullable=True, comment='Пароль для доступа к инвертору'))
    op.add_column('energetic_objects', sa.Column('timezone', sa.String(), server_default='Europe/Kiev', nullable=False, comment='Часовой пояс объекта (например: Europe/Kiev)'))
    op.drop_constraint('energy_managers_energy_manager_cor_id_fkey', 'energy_managers', type_='foreignkey')
    op.create_foreign_key(None, 'energy_managers', 'users', ['energy_manager_cor_id'], ['cor_id'])
    op.drop_constraint('lab_assistants_lab_assistant_cor_id_fkey', 'lab_assistants', type_='foreignkey')
    op.create_foreign_key(None, 'lab_assistants', 'users', ['lab_assistant_cor_id'], ['cor_id'])
    op.drop_constraint('lawyers_lawyer_cor_id_fkey', 'lawyers', type_='foreignkey')
    op.create_foreign_key(None, 'lawyers', 'users', ['lawyer_cor_id'], ['cor_id'])
    op.drop_constraint('user_sessions_user_id_fkey', 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['cor_id'])
    op.create_index(op.f('ix_users_cor_id'), 'users', ['cor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cor_id'), table_name='users')
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key('user_sessions_user_id_fkey', 'user_sessions', 'users', ['user_id'], ['cor_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lawyers', type_='foreignkey')
    op.create_foreign_key('lawyers_lawyer_cor_id_fkey', 'lawyers', 'users', ['lawyer_cor_id'], ['cor_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lab_assistants', type_='foreignkey')
    op.create_foreign_key('lab_assistants_lab_assistant_cor_id_fkey', 'lab_assistants', 'users', ['lab_assistant_cor_id'], ['cor_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'energy_managers', type_='foreignkey')
    op.create_foreign_key('energy_managers_energy_manager_cor_id_fkey', 'energy_managers', 'users', ['energy_manager_cor_id'], ['cor_id'], ondelete='CASCADE')
    op.drop_column('energetic_objects', 'timezone')
    op.drop_column('energetic_objects', 'inverter_password')
    op.drop_column('energetic_objects', 'inverter_login')
    op.drop_column('energetic_objects', 'port')
    op.drop_column('energetic_objects', 'ip_address')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key('doctors_doctor_id_fkey', 'doctors', 'users', ['doctor_id'], ['cor_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key('devices_user_id_fkey', 'devices', 'users', ['user_id'], ['cor_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'device_access', type_='foreignkey')
    op.drop_constraint(None, 'device_access', type_='foreignkey')
    op.create_foreign_key('device_access_accessing_user_id_fkey', 'device_access', 'users', ['accessing_user_id'], ['cor_id'], ondelete='CASCADE')
    op.create_foreign_key('device_access_granting_user_id_fkey', 'device_access', 'users', ['granting_user_id'], ['cor_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_fuel_station_qr_sessions_user_cor_id'), table_name='fuel_station_qr_sessions')
    op.drop_index(op.f('ix_fuel_station_qr_sessions_session_token'), table_name='fuel_station_qr_sessions')
    op.drop_index('idx_fuel_qr_user', table_name='fuel_station_qr_sessions')
    op.drop_index('idx_fuel_qr_token', table_name='fuel_station_qr_sessions')
    op.drop_index('idx_fuel_qr_created', table_name='fuel_station_qr_sessions')
    op.drop_table('fuel_station_qr_sessions')
    op.drop_table('financiers')
    op.drop_index('idx_finance_auth_service', table_name='finance_backend_auth')
    op.drop_table('finance_backend_auth')
    # ### end Alembic commands ###
