"""final_phase2_validation

Revision ID: ed29ac91f9f7
Revises: c107213c329f
Create Date: 2025-11-13 12:50:41.752995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed29ac91f9f7'
down_revision: Union[str, None] = 'c107213c329f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corporate_clients', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID клиента',
               existing_nullable=False)
    op.alter_column('corporate_clients', 'owner_cor_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               comment=None,
               existing_comment='COR ID владельца компании',
               existing_nullable=False)
    op.alter_column('corporate_clients', 'company_format',
               existing_type=sa.VARCHAR(length=50),
               comment='Форма підприємства: ТОВ, ФОП, ПП',
               existing_comment='Форма підприємства (ТОВ, ФОП, ПП)',
               existing_nullable=False)
    op.alter_column('corporate_clients', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус: pending (на рассмотрении), active (активна), blocked (заблокирована), rejected (отклонена), limit_exceeded (превышен лимит)',
               existing_comment='Статус: pending, active, blocked, rejected, limit_exceeded',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('corporate_clients', 'finance_company_id',
               existing_type=sa.INTEGER(),
               comment='ID компании в финансовом бэкенде',
               existing_comment='ID компании в finance backend',
               existing_nullable=True)
    op.alter_column('corporate_clients', 'reviewed_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               comment='Кто рассмотрел/изменил статус',
               existing_comment='COR ID модератора',
               existing_nullable=True)
    op.alter_column('corporate_clients', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда изменён статус',
               existing_comment='Время модерации',
               existing_nullable=True)
    op.alter_column('corporate_clients', 'rejection_reason',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               comment='Причина отклонения (если rejected)',
               existing_comment='Причина отклонения/блокировки',
               existing_nullable=True)
    op.alter_column('corporate_clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата создания заявки',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('corporate_clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата последнего обновления',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_corporate_clients_created_at', table_name='corporate_clients')
    op.drop_index('ix_corporate_clients_finance_company_id', table_name='corporate_clients')
    op.drop_index('ix_corporate_clients_status', table_name='corporate_clients')
    op.drop_index('ix_corporate_clients_tax_id', table_name='corporate_clients')
    op.create_index('idx_corp_client_created', 'corporate_clients', ['created_at'], unique=False)
    op.create_index('idx_corp_client_finance_id', 'corporate_clients', ['finance_company_id'], unique=False)
    op.create_index('idx_corp_client_owner', 'corporate_clients', ['owner_cor_id'], unique=False)
    op.create_index('idx_corp_client_status', 'corporate_clients', ['status'], unique=False)
    op.create_unique_constraint(None, 'corporate_clients', ['finance_company_id'])
    op.create_unique_constraint(None, 'corporate_clients', ['company_name'])
    op.create_unique_constraint(None, 'corporate_clients', ['tax_id'])
    op.drop_table_comment(
        'corporate_clients',
        existing_comment='Корпоративные клиенты топливной системы',
        schema=None
    )
    op.drop_index('ix_device_access_id', table_name='device_access')
    op.drop_constraint('device_access_granting_user_id_fkey', 'device_access', type_='foreignkey')
    op.drop_constraint('device_access_accessing_user_id_fkey', 'device_access', type_='foreignkey')
    op.create_foreign_key(None, 'device_access', 'users', ['granting_user_id'], ['cor_id'])
    op.create_foreign_key(None, 'device_access', 'users', ['accessing_user_id'], ['cor_id'])
    op.alter_column('devices', 'name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('ix_devices_id', table_name='devices')
    op.drop_index('ix_devices_token', table_name='devices')
    op.create_unique_constraint(None, 'devices', ['token'])
    op.drop_constraint('devices_user_id_fkey', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'users', ['user_id'], ['cor_id'])
    op.drop_constraint('doctors_doctor_id_fkey', 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'users', ['doctor_id'], ['cor_id'])
    op.alter_column('energetic_objects', 'protocol',
               existing_type=sa.VARCHAR(),
               comment='Протокол связи',
               existing_comment='Протокол связи (modbus, http, mqtt и т.д.)',
               existing_nullable=True)
    op.alter_column('energetic_objects', 'timezone',
               existing_type=sa.VARCHAR(),
               comment='Часовой пояс объекта (например: Europe/Kiev)',
               existing_comment='Часовой пояс объекта (например: Europe/Kiev, America/New_York)',
               existing_nullable=False,
               existing_server_default=sa.text("'Europe/Kiev'::character varying"))
    op.drop_constraint('energy_managers_energy_manager_cor_id_fkey', 'energy_managers', type_='foreignkey')
    op.create_foreign_key(None, 'energy_managers', 'users', ['energy_manager_cor_id'], ['cor_id'])
    op.alter_column('finance_backend_auth', 'service_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Название сервиса (finance_backend)',
               existing_nullable=False)
    op.alter_column('finance_backend_auth', 'api_endpoint',
               existing_type=sa.VARCHAR(length=500),
               comment='URL бэкенда финансов',
               existing_nullable=False)
    op.alter_column('finance_backend_auth', 'totp_secret',
               existing_type=postgresql.BYTEA(),
               comment='Зашифрованный TOTP секрет',
               existing_nullable=False)
    op.alter_column('finance_backend_auth', 'totp_interval',
               existing_type=sa.INTEGER(),
               comment='Интервал TOTP в секундах',
               existing_nullable=False)
    op.alter_column('finance_backend_auth', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Активна ли интеграция',
               existing_nullable=False)
    op.alter_column('finance_backend_auth', 'last_successful_auth',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Последняя успешная авторизация',
               existing_nullable=True)
    op.alter_column('finance_backend_auth', 'last_failed_auth',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Последняя неудачная авторизация',
               existing_nullable=True)
    op.alter_column('finance_backend_auth', 'failed_attempts',
               existing_type=sa.INTEGER(),
               comment='Количество неудачных попыток подряд',
               existing_nullable=False)
    op.drop_index('ix_finance_backend_is_active', table_name='finance_backend_auth')
    op.drop_index('ix_finance_backend_service_name', table_name='finance_backend_auth')
    op.create_index('idx_finance_auth_service', 'finance_backend_auth', ['service_name'], unique=False)
    op.drop_index('ix_financiers_financier_cor_id', table_name='financiers')
    op.drop_constraint('financiers_financier_cor_id_fkey', 'financiers', type_='foreignkey')
    op.create_foreign_key(None, 'financiers', 'users', ['financier_cor_id'], ['cor_id'])
    op.alter_column('first_aid_kit_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('fuel_station_qr_sessions', 'session_token',
               existing_type=sa.VARCHAR(length=255),
               comment='Уникальный токен сессии',
               existing_nullable=False)
    op.alter_column('fuel_station_qr_sessions', 'totp_code',
               existing_type=sa.VARCHAR(length=10),
               comment='TOTP код на момент генерации',
               existing_nullable=False)
    op.alter_column('fuel_station_qr_sessions', 'timestamp_token',
               existing_type=sa.VARCHAR(length=255),
               comment='Timestamp токен для защиты от replay атак',
               existing_nullable=False)
    op.alter_column('fuel_station_qr_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Время создания QR кода',
               existing_nullable=False)
    op.alter_column('fuel_station_qr_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Время истечения QR кода',
               existing_nullable=False)
    op.alter_column('fuel_station_qr_sessions', 'is_used',
               existing_type=sa.BOOLEAN(),
               comment='Был ли использован QR код',
               existing_nullable=False)
    op.alter_column('fuel_station_qr_sessions', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Время использования',
               existing_nullable=True)
    op.drop_constraint('fuel_station_qr_sessions_session_token_key', 'fuel_station_qr_sessions', type_='unique')
    op.drop_index('ix_fuel_qr_expires_at', table_name='fuel_station_qr_sessions')
    op.drop_index('ix_fuel_qr_is_used', table_name='fuel_station_qr_sessions')
    op.drop_index('ix_fuel_qr_session_token', table_name='fuel_station_qr_sessions')
    op.drop_index('ix_fuel_qr_user_cor_id', table_name='fuel_station_qr_sessions')
    op.create_index('idx_fuel_qr_created', 'fuel_station_qr_sessions', ['created_at'], unique=False)
    op.create_index('idx_fuel_qr_token', 'fuel_station_qr_sessions', ['session_token'], unique=False)
    op.create_index('idx_fuel_qr_user', 'fuel_station_qr_sessions', ['user_cor_id'], unique=False)
    op.create_index(op.f('ix_fuel_station_qr_sessions_session_token'), 'fuel_station_qr_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_fuel_station_qr_sessions_user_cor_id'), 'fuel_station_qr_sessions', ['user_cor_id'], unique=False)
    op.drop_constraint('lab_assistants_lab_assistant_cor_id_fkey', 'lab_assistants', type_='foreignkey')
    op.create_foreign_key(None, 'lab_assistants', 'users', ['lab_assistant_cor_id'], ['cor_id'])
    op.drop_constraint('lawyers_lawyer_cor_id_fkey', 'lawyers', type_='foreignkey')
    op.create_foreign_key(None, 'lawyers', 'users', ['lawyer_cor_id'], ['cor_id'])
    op.drop_index('ix_manufactured_devices_id', table_name='manufactured_devices')
    op.drop_index('ix_manufactured_devices_token', table_name='manufactured_devices')
    op.create_unique_constraint(None, 'manufactured_devices', ['token'])
    op.drop_index('idx_medical_card_access_card', table_name='medical_card_access')
    op.drop_constraint('uq_card_user_access', 'medical_card_access', type_='unique')
    op.create_index('idx_medical_card_access_card_user', 'medical_card_access', ['medical_card_id', 'user_cor_id'], unique=False)
    op.alter_column('medicine_intakes', 'planned_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('medicine_intakes', 'actual_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('medicine_intakes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('medicine_intakes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_medicine_intakes_planned_datetime', table_name='medicine_intakes')
    op.drop_index('idx_medicine_intakes_schedule_id', table_name='medicine_intakes')
    op.drop_index('idx_medicine_intakes_status', table_name='medicine_intakes')
    op.drop_index('idx_medicine_intakes_user_cor_id', table_name='medicine_intakes')
    op.alter_column('medicine_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('medicine_schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('medicines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('medicines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_medicines_name', table_name='medicines')
    op.drop_index('ix_printing_device_id', table_name='printing_device')
    op.drop_constraint('user_sessions_user_id_fkey', 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['cor_id'])
    op.create_index(op.f('ix_users_cor_id'), 'users', ['cor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cor_id'), table_name='users')
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key('user_sessions_user_id_fkey', 'user_sessions', 'users', ['user_id'], ['cor_id'], ondelete='CASCADE')
    op.create_index('ix_printing_device_id', 'printing_device', ['id'], unique=False)
    op.create_index('idx_medicines_name', 'medicines', ['name'], unique=False)
    op.alter_column('medicines', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('medicines', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('medicine_schedules', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('medicine_schedules', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index('idx_medicine_intakes_user_cor_id', 'medicine_intakes', ['user_cor_id'], unique=False)
    op.create_index('idx_medicine_intakes_status', 'medicine_intakes', ['status'], unique=False)
    op.create_index('idx_medicine_intakes_schedule_id', 'medicine_intakes', ['schedule_id'], unique=False)
    op.create_index('idx_medicine_intakes_planned_datetime', 'medicine_intakes', ['planned_datetime'], unique=False)
    op.alter_column('medicine_intakes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('medicine_intakes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('medicine_intakes', 'actual_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('medicine_intakes', 'planned_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index('idx_medical_card_access_card_user', table_name='medical_card_access')
    op.create_unique_constraint('uq_card_user_access', 'medical_card_access', ['medical_card_id', 'user_cor_id'])
    op.create_index('idx_medical_card_access_card', 'medical_card_access', ['medical_card_id'], unique=False)
    op.drop_constraint(None, 'manufactured_devices', type_='unique')
    op.create_index('ix_manufactured_devices_token', 'manufactured_devices', ['token'], unique=True)
    op.create_index('ix_manufactured_devices_id', 'manufactured_devices', ['id'], unique=False)
    op.drop_constraint(None, 'lawyers', type_='foreignkey')
    op.create_foreign_key('lawyers_lawyer_cor_id_fkey', 'lawyers', 'users', ['lawyer_cor_id'], ['cor_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lab_assistants', type_='foreignkey')
    op.create_foreign_key('lab_assistants_lab_assistant_cor_id_fkey', 'lab_assistants', 'users', ['lab_assistant_cor_id'], ['cor_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_fuel_station_qr_sessions_user_cor_id'), table_name='fuel_station_qr_sessions')
    op.drop_index(op.f('ix_fuel_station_qr_sessions_session_token'), table_name='fuel_station_qr_sessions')
    op.drop_index('idx_fuel_qr_user', table_name='fuel_station_qr_sessions')
    op.drop_index('idx_fuel_qr_token', table_name='fuel_station_qr_sessions')
    op.drop_index('idx_fuel_qr_created', table_name='fuel_station_qr_sessions')
    op.create_index('ix_fuel_qr_user_cor_id', 'fuel_station_qr_sessions', ['user_cor_id'], unique=False)
    op.create_index('ix_fuel_qr_session_token', 'fuel_station_qr_sessions', ['session_token'], unique=False)
    op.create_index('ix_fuel_qr_is_used', 'fuel_station_qr_sessions', ['is_used'], unique=False)
    op.create_index('ix_fuel_qr_expires_at', 'fuel_station_qr_sessions', ['expires_at'], unique=False)
    op.create_unique_constraint('fuel_station_qr_sessions_session_token_key', 'fuel_station_qr_sessions', ['session_token'])
    op.alter_column('fuel_station_qr_sessions', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Время использования',
               existing_nullable=True)
    op.alter_column('fuel_station_qr_sessions', 'is_used',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Был ли использован QR код',
               existing_nullable=False)
    op.alter_column('fuel_station_qr_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Время истечения QR кода',
               existing_nullable=False)
    op.alter_column('fuel_station_qr_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Время создания QR кода',
               existing_nullable=False)
    op.alter_column('fuel_station_qr_sessions', 'timestamp_token',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Timestamp токен для защиты от replay атак',
               existing_nullable=False)
    op.alter_column('fuel_station_qr_sessions', 'totp_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='TOTP код на момент генерации',
               existing_nullable=False)
    op.alter_column('fuel_station_qr_sessions', 'session_token',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Уникальный токен сессии',
               existing_nullable=False)
    op.alter_column('first_aid_kit_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'financiers', type_='foreignkey')
    op.create_foreign_key('financiers_financier_cor_id_fkey', 'financiers', 'users', ['financier_cor_id'], ['cor_id'], ondelete='CASCADE')
    op.create_index('ix_financiers_financier_cor_id', 'financiers', ['financier_cor_id'], unique=False)
    op.drop_index('idx_finance_auth_service', table_name='finance_backend_auth')
    op.create_index('ix_finance_backend_service_name', 'finance_backend_auth', ['service_name'], unique=False)
    op.create_index('ix_finance_backend_is_active', 'finance_backend_auth', ['is_active'], unique=False)
    op.alter_column('finance_backend_auth', 'failed_attempts',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Количество неудачных попыток подряд',
               existing_nullable=False)
    op.alter_column('finance_backend_auth', 'last_failed_auth',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Последняя неудачная авторизация',
               existing_nullable=True)
    op.alter_column('finance_backend_auth', 'last_successful_auth',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Последняя успешная авторизация',
               existing_nullable=True)
    op.alter_column('finance_backend_auth', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Активна ли интеграция',
               existing_nullable=False)
    op.alter_column('finance_backend_auth', 'totp_interval',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Интервал TOTP в секундах',
               existing_nullable=False)
    op.alter_column('finance_backend_auth', 'totp_secret',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='Зашифрованный TOTP секрет',
               existing_nullable=False)
    op.alter_column('finance_backend_auth', 'api_endpoint',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL бэкенда финансов',
               existing_nullable=False)
    op.alter_column('finance_backend_auth', 'service_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Название сервиса (finance_backend)',
               existing_nullable=False)
    op.drop_constraint(None, 'energy_managers', type_='foreignkey')
    op.create_foreign_key('energy_managers_energy_manager_cor_id_fkey', 'energy_managers', 'users', ['energy_manager_cor_id'], ['cor_id'], ondelete='CASCADE')
    op.alter_column('energetic_objects', 'timezone',
               existing_type=sa.VARCHAR(),
               comment='Часовой пояс объекта (например: Europe/Kiev, America/New_York)',
               existing_comment='Часовой пояс объекта (например: Europe/Kiev)',
               existing_nullable=False,
               existing_server_default=sa.text("'Europe/Kiev'::character varying"))
    op.alter_column('energetic_objects', 'protocol',
               existing_type=sa.VARCHAR(),
               comment='Протокол связи (modbus, http, mqtt и т.д.)',
               existing_comment='Протокол связи',
               existing_nullable=True)
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key('doctors_doctor_id_fkey', 'doctors', 'users', ['doctor_id'], ['cor_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key('devices_user_id_fkey', 'devices', 'users', ['user_id'], ['cor_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'devices', type_='unique')
    op.create_index('ix_devices_token', 'devices', ['token'], unique=True)
    op.create_index('ix_devices_id', 'devices', ['id'], unique=False)
    op.alter_column('devices', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.drop_constraint(None, 'device_access', type_='foreignkey')
    op.drop_constraint(None, 'device_access', type_='foreignkey')
    op.create_foreign_key('device_access_accessing_user_id_fkey', 'device_access', 'users', ['accessing_user_id'], ['cor_id'], ondelete='CASCADE')
    op.create_foreign_key('device_access_granting_user_id_fkey', 'device_access', 'users', ['granting_user_id'], ['cor_id'], ondelete='CASCADE')
    op.create_index('ix_device_access_id', 'device_access', ['id'], unique=False)
    op.create_table_comment(
        'corporate_clients',
        'Корпоративные клиенты топливной системы',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'corporate_clients', type_='unique')
    op.drop_constraint(None, 'corporate_clients', type_='unique')
    op.drop_constraint(None, 'corporate_clients', type_='unique')
    op.drop_index('idx_corp_client_status', table_name='corporate_clients')
    op.drop_index('idx_corp_client_owner', table_name='corporate_clients')
    op.drop_index('idx_corp_client_finance_id', table_name='corporate_clients')
    op.drop_index('idx_corp_client_created', table_name='corporate_clients')
    op.create_index('ix_corporate_clients_tax_id', 'corporate_clients', ['tax_id'], unique=True)
    op.create_index('ix_corporate_clients_status', 'corporate_clients', ['status'], unique=False)
    op.create_index('ix_corporate_clients_finance_company_id', 'corporate_clients', ['finance_company_id'], unique=False)
    op.create_index('ix_corporate_clients_created_at', 'corporate_clients', ['created_at'], unique=False)
    op.alter_column('corporate_clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата последнего обновления',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('corporate_clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата создания заявки',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('corporate_clients', 'rejection_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               comment='Причина отклонения/блокировки',
               existing_comment='Причина отклонения (если rejected)',
               existing_nullable=True)
    op.alter_column('corporate_clients', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Время модерации',
               existing_comment='Когда изменён статус',
               existing_nullable=True)
    op.alter_column('corporate_clients', 'reviewed_by',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               comment='COR ID модератора',
               existing_comment='Кто рассмотрел/изменил статус',
               existing_nullable=True)
    op.alter_column('corporate_clients', 'finance_company_id',
               existing_type=sa.INTEGER(),
               comment='ID компании в finance backend',
               existing_comment='ID компании в финансовом бэкенде',
               existing_nullable=True)
    op.alter_column('corporate_clients', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус: pending, active, blocked, rejected, limit_exceeded',
               existing_comment='Статус: pending (на рассмотрении), active (активна), blocked (заблокирована), rejected (отклонена), limit_exceeded (превышен лимит)',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('corporate_clients', 'company_format',
               existing_type=sa.VARCHAR(length=50),
               comment='Форма підприємства (ТОВ, ФОП, ПП)',
               existing_comment='Форма підприємства: ТОВ, ФОП, ПП',
               existing_nullable=False)
    op.alter_column('corporate_clients', 'owner_cor_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               comment='COR ID владельца компании',
               existing_nullable=False)
    op.alter_column('corporate_clients', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID клиента',
               existing_nullable=False)
    # ### end Alembic commands ###
