"""broadcast_interval_as_float_v1_4_8

Revision ID: f60d5cdd7f7f
Revises: 34310b7ed291
Create Date: 2025-12-18 10:36:35.616943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f60d5cdd7f7f'
down_revision: Union[str, None] = '34310b7ed291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corporate_clients', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус: pending (на рассмотрении), active (активна), blocked (заблокирована), rejected (отклонена), limit_exceeded (превышен лимит), deleted (удалена)',
               existing_comment='Статус: pending (на рассмотрении), active (активна), blocked (заблокирована), rejected (отклонена), limit_exceeded (превышен лимит)',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('device_polling_tasks', 'interval_seconds',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_comment='Интервал опроса в секундах',
               existing_nullable=False)
    op.alter_column('websocket_broadcast_tasks', 'interval_seconds',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_comment='Интервал отправки команды в секундах',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('websocket_broadcast_tasks', 'interval_seconds',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_comment='Интервал отправки команды в секундах',
               existing_nullable=False)
    op.alter_column('device_polling_tasks', 'interval_seconds',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_comment='Интервал опроса в секундах',
               existing_nullable=False)
    op.alter_column('corporate_clients', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус: pending (на рассмотрении), active (активна), blocked (заблокирована), rejected (отклонена), limit_exceeded (превышен лимит)',
               existing_comment='Статус: pending (на рассмотрении), active (активна), blocked (заблокирована), rejected (отклонена), limit_exceeded (превышен лимит), deleted (удалена)',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###
