"""Rebuild migration 10.11.2025

Revision ID: fd8ded0a70b2
Revises: 2418c1445994
Create Date: 2025-11-11 11:19:28.982469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8ded0a70b2'
down_revision: Union[str, None] = '2418c1445994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users DROP CONSTRAINT users_cor_id_key CASCADE')

    op.create_index(
        'users_cor_id_key',
        'users',
        ['cor_id'],
        unique=True
    )
    
    fk_to_create = [
        ('devices', 'devices_user_id_fkey', 'user_id', 'CASCADE'),
        ('doctors', 'doctors_doctor_id_fkey', 'doctor_id', 'CASCADE'),
        ('energy_managers', 'energy_managers_energy_manager_cor_id_fkey', 'energy_manager_cor_id', 'CASCADE'),
        ('lab_assistants', 'lab_assistants_lab_assistant_cor_id_fkey', 'lab_assistant_cor_id', 'CASCADE'),
        ('user_sessions', 'user_sessions_user_id_fkey', 'user_id', 'CASCADE'),
        ('device_access', 'device_access_accessing_user_id_fkey', 'accessing_user_id', 'CASCADE'),
        ('device_access', 'device_access_granting_user_id_fkey', 'granting_user_id', 'CASCADE'),
        ('lawyers', 'lawyers_lawyer_cor_id_fkey', 'lawyer_cor_id', 'CASCADE'),
        ('first_aid_kits', 'first_aid_kits_user_cor_id_fkey', 'user_cor_id', 'CASCADE'),
        ('medicine_schedules', 'medicine_schedules_user_cor_id_fkey', 'user_cor_id', 'CASCADE'),
        ('prescription_files', 'prescription_files_user_cor_id_fkey', 'user_cor_id', 'CASCADE'),
        ('medicine_intakes', 'medicine_intakes_user_cor_id_fkey', 'user_cor_id', 'CASCADE'),
        ('medical_card_access', 'medical_card_access_user_cor_id_fkey', 'user_cor_id', 'CASCADE'),
        ('medical_card_access', 'medical_card_access_granted_by_cor_id_fkey', 'granted_by_cor_id', None),
        ('medical_cards', 'medical_cards_owner_cor_id_fkey', 'owner_cor_id', 'CASCADE'),
    ]
    
    for table_name, constraint_name, column_name, ondelete in fk_to_create:
        op.create_foreign_key(
            constraint_name,
            table_name,
            'users',
            [column_name],
            ['cor_id'],
            ondelete=ondelete
        )




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
